Github Reference Link https://github.com/krishnaik06/Machine-Learning-in-90-days

In [1]:
fname="Abhi"
lname="Patel"

In [2]:
print("My full name is {} : {}".format(fname,lname))

My full name is Abhi : Patel


In [3]:
print("My full name is {} : {}".format(lname,fname))

My full name is Patel : Abhi


In [4]:
print("My full name is {l} : {f}".format(l=lname,f=fname))

My full name is Patel : Abhi


In [5]:
len("AbhiP")

5

In [6]:
type(['1','2','3'])

list

Like VS Code (Ctrl + Space)we can use Tab in jupyter

In [7]:
custom_lst=['A','B',3,4,7]

In [10]:
custom_lst.append("Abhi")

In [11]:
custom_lst

['A', 'B', 3, 4, 7, 'Abhi']

In [13]:
set_var={"D","F",9}
set_var

{9, 'D', 'F'}

In [1]:
my_dict={"Car1": "Audi", "Car2":"BMW","Car3":"Mercidies Benz"}

Lists

A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes, lists are defined by having values between square brackets [ ]

SETS

A Set is an unordered collection data type that is iterable, mutable, and has no duplicate elements. Python's set class represents the mathematical notion of a set.This is based on a data structure known as a hash table.

Dictionaries

A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values.

What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [6]:
import numpy as np

my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

print(arr)

[1 2 3 4 5]


In [7]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [8]:
arr.shape

(3, 5)

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
val=2

arr[arr<3]

array([1, 2, 2])

In [13]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])